// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbfvI8oZrQZ6B6CYgc5IOu2HhYUzVmPE',
    appId: '1:545796750946:web:8f164b9a69f6915ae19b3b',
    messagingSenderId: '545796750946',
    projectId: 'practapp-feb91',
    authDomain: 'practapp-feb91.firebaseapp.com',
    storageBucket: 'practapp-feb91.appspot.com',
    measurementId: 'G-T7BMDWVYME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC36kPd-GYYC8b5jUxYVMEkG4Ii9Qcjac',
    appId: '1:545796750946:android:47331bbedcd3daade19b3b',
    messagingSenderId: '545796750946',
    projectId: 'practapp-feb91',
    storageBucket: 'practapp-feb91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDHGoWUwLmOtBTNUkWuiLzpnJmpHoGps',
    appId: '1:545796750946:ios:9e8bf440c0dbd320e19b3b',
    messagingSenderId: '545796750946',
    projectId: 'practapp-feb91',
    storageBucket: 'practapp-feb91.appspot.com',
    iosClientId: '545796750946-3atdvsujfqic0ck78t1433r1ckbi8i0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.practApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFDHGoWUwLmOtBTNUkWuiLzpnJmpHoGps',
    appId: '1:545796750946:ios:9e8bf440c0dbd320e19b3b',
    messagingSenderId: '545796750946',
    projectId: 'practapp-feb91',
    storageBucket: 'practapp-feb91.appspot.com',
    iosClientId: '545796750946-3atdvsujfqic0ck78t1433r1ckbi8i0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.practApp',
  );
}
